### ISSUE TITLE
Error when timescaledb database contains dropped chunks with tombstone

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/doctor#26]
When run against a database with a dropped chunk tombstone, that is entries matching:

```SQL
SELECT * FROM _timescaledb_catalog.chunk WHERE dropped;
```

```bash
> psql postgres://postgres:1@localhost:5433 -c "SELECT * FROM _timescaledb_catalog.chunk WHERE dropped;"
 id | hypertable_id |      schema_name      |    table_name     | compressed_chunk_id | dropped | status | osm_chunk
----+---------------+-----------------------+-------------------+---------------------+---------+--------+-----------
 20 |             2 | _timescaledb_internal | _hyper_2_20_chunk |                     | t       |      0 | f
(1 row)
```

timescale-doctor fails:

```bash
> timescale-doctor postgres://postgres:1@localhost:5433
Traceback (most recent call last):
  File "/home/james/workspace/doctor/venv/bin/timescale-doctor", line 8, in <module>
    sys.exit(main())
  File "/home/james/workspace/doctor/venv/lib/python3.10/site-packages/doctor/cli.py", line 57, in main
    check_rules(dsn)
  File "/home/james/workspace/doctor/venv/lib/python3.10/site-packages/doctor/__init__.py", line 83, in check_rules
    for report in rule.execute(conn, rule.message):
  File "/home/james/workspace/doctor/venv/lib/python3.10/site-packages/doctor/__init__.py", line 62, in execute
    cursor.execute(self.query) # pylint: disable=E1101
  File "/nix/store/khvw06lqds60i0npy58zs27xpwb8x0d9-python3.10-psycopg2-2.9.5/lib/python3.10/site-packages/psycopg2/extras.py", line 236, in execute
    return super().execute(query, vars)
psycopg2.errors.UndefinedTable: relation "_timescaledb_internal._hyper_2_20_chunk" does not exist
```

**Comment by mkindahl** [comment]
Trivial to reproduce using the following definition:

```sql
CREATE TABLE conditions(
    time TIMESTAMPTZ NOT NULL,
    device INTEGER,
    temperature FLOAT
);

SELECT * FROM create_hypertable('conditions', 'time',
       chunk_time_interval => INTERVAL '1 day');

INSERT INTO conditions
SELECT time, (random()*30)::int, random()*80 - 40
FROM generate_series(now() - '1 month'::interval,
     		     now(),
		     INTERVAL '1 min') AS time;

CREATE MATERIALIZED VIEW conditions_summary_hourly
WITH (timescaledb.continuous) AS
SELECT device,
       time_bucket('1 hour', "time") AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device, bucket
WITH NO DATA;

SELECT id AS hypertable_id
  FROM _timescaledb_catalog.hypertable
 WHERE table_name = 'conditions' \gset

SELECT count(*) FROM _timescaledb_catalog.chunk WHERE hypertable_id = :hypertable_id AND dropped;

SELECT drop_chunks('conditions', now() - '2 weeks'::interval);
```

The problem is in the `ChunkPermission` rule.
